//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anti__Bot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TranslatesList {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TranslatesList() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Anti__Bot.Properties.TranslatesList", typeof(TranslatesList).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cops in GURPS.
        /// </summary>
        internal static string _3edCops1 {
            get {
                return ResourceManager.GetString("3edCops1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://drive.google.com/file/d/1XhJKGJYgkMQBUawQC7VA0ql44jbus7wf/view.
        /// </summary>
        internal static string _3edCops1Link {
            get {
                return ResourceManager.GetString("3edCops1Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GURPS City Stats.
        /// </summary>
        internal static string CityStats {
            get {
                return ResourceManager.GetString("CityStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://drive.google.com/file/d/1YTxx5no5S4Cv2nlxt9MdPZxeClrd1nFD/view.
        /// </summary>
        internal static string CityStatsLink {
            get {
                return ResourceManager.GetString("CityStatsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designer&apos;s Notes GURPS Spaceships.
        /// </summary>
        internal static string DesNotesSpace1 {
            get {
                return ResourceManager.GetString("DesNotesSpace1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://drive.google.com/file/d/1PjSfybiB7O1yZ6gH58PFt_LivTToafZW/view.
        /// </summary>
        internal static string DesNotesSpace1Link {
            get {
                return ResourceManager.GetString("DesNotesSpace1Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand Loyalty.
        /// </summary>
        internal static string HomeRuleBrandLoyalty {
            get {
                return ResourceManager.GetString("HomeRuleBrandLoyalty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand Loyalty Death Blockers.
        /// </summary>
        internal static string HomeRuleBrandLoyaltyExp {
            get {
                return ResourceManager.GetString("HomeRuleBrandLoyaltyExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://drive.google.com/file/d/127QR0voyyfxHB3PwARoLrRQL2WEHolxs/view.
        /// </summary>
        internal static string HomeRuleBrandLoyaltyExpLink {
            get {
                return ResourceManager.GetString("HomeRuleBrandLoyaltyExpLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://drive.google.com/file/d/1r30yH-kJXlA6nbtRuAV8NFo9_x0dBAxq/view.
        /// </summary>
        internal static string HomeRuleBrandLoyaltyLink {
            get {
                return ResourceManager.GetString("HomeRuleBrandLoyaltyLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passive Visual Sensor Design System.
        /// </summary>
        internal static string HomeRulePassiveSensor {
            get {
                return ResourceManager.GetString("HomeRulePassiveSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://drive.google.com/file/d/0B2eXj-PYOUDMMXNCZnFpZVdMT3M/view.
        /// </summary>
        internal static string HomeRulePassiveSensorLink {
            get {
                return ResourceManager.GetString("HomeRulePassiveSensorLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Armor, Powered Up!.
        /// </summary>
        internal static string HomeRulePowerArmorPowered {
            get {
                return ResourceManager.GetString("HomeRulePowerArmorPowered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://drive.google.com/file/d/19-up92U-TmJx5-bsSwIGW7kXSGOdH9gV/view.
        /// </summary>
        internal static string HomeRulePowerArmorPoweredLink {
            get {
                return ResourceManager.GetString("HomeRulePowerArmorPoweredLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultra-Tech Ultra-Gear 30mm Gyroc.
        /// </summary>
        internal static string HomeRuleUltraGear30mm {
            get {
                return ResourceManager.GetString("HomeRuleUltraGear30mm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://drive.google.com/file/d/11L2Hk5Fm0q9vPRwZsMCsyfHuyDOUClON/view.
        /// </summary>
        internal static string HomeRuleUltraGear30mmLink {
            get {
                return ResourceManager.GetString("HomeRuleUltraGear30mmLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultra-Tech Ultra-Quickie Electrolaser Design.
        /// </summary>
        internal static string HomeRuleUTElectroLaser {
            get {
                return ResourceManager.GetString("HomeRuleUTElectroLaser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://drive.google.com/file/d/1bHKVSzTidr5Gvd6IgquxIriDQRrOb1gY/view.
        /// </summary>
        internal static string HomeRuleUTElectroLaserLink {
            get {
                return ResourceManager.GetString("HomeRuleUTElectroLaserLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GURPS Mass Combat.
        /// </summary>
        internal static string MassCombat {
            get {
                return ResourceManager.GetString("MassCombat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://drive.google.com/file/d/1BqfQWBdRQO-7QHJtaV5Ev7kuX0N8EoYt/view.
        /// </summary>
        internal static string MassCombatLink {
            get {
                return ResourceManager.GetString("MassCombatLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mad as Bones.
        /// </summary>
        internal static string Py103MadAsBones {
            get {
                return ResourceManager.GetString("Py103MadAsBones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://drive.google.com/file/d/1Ueh5O5u05dHhSqDuI2KYgWckNQLUr_bN/view.
        /// </summary>
        internal static string Py103MadAsBonesLink {
            get {
                return ResourceManager.GetString("Py103MadAsBonesLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spaceship Malfunctions.
        /// </summary>
        internal static string Py103SSMalf {
            get {
                return ResourceManager.GetString("Py103SSMalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://drive.google.com/file/d/13IFOJri4C7J4PE4_moFGnhijzX5uXcTT/view.
        /// </summary>
        internal static string Py103SSMalfLink {
            get {
                return ResourceManager.GetString("Py103SSMalfLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animal Combat.
        /// </summary>
        internal static string Py111AnimalCombat {
            get {
                return ResourceManager.GetString("Py111AnimalCombat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://drive.google.com/file/d/1ldDBvJOEaYl6iHrTAybjYRXo7fb7IgED/view.
        /// </summary>
        internal static string Py111AnimalCombatLink {
            get {
                return ResourceManager.GetString("Py111AnimalCombatLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternate Spaceships.
        /// </summary>
        internal static string Py34AlternateSS {
            get {
                return ResourceManager.GetString("Py34AlternateSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://drive.google.com/file/d/11LQfpeSjSwDu_K0pWRzq9_4UBf0zfqyk/view.
        /// </summary>
        internal static string Py34AlternateSSLink {
            get {
                return ResourceManager.GetString("Py34AlternateSSLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blaster And Laser Design.
        /// </summary>
        internal static string Py37BLDesign {
            get {
                return ResourceManager.GetString("Py37BLDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://drive.google.com/file/d/1wvUfX9JAOiK9UpSikegcnOX4uusrmFb8/view.
        /// </summary>
        internal static string Py37BLDesignLink {
            get {
                return ResourceManager.GetString("Py37BLDesignLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thinking Machines.
        /// </summary>
        internal static string Py37ThinkingMachines {
            get {
                return ResourceManager.GetString("Py37ThinkingMachines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://drive.google.com/file/d/0B2eXj-PYOUDMUzAxRVdId2pENjg/view.
        /// </summary>
        internal static string Py37ThinkingMachinesLink {
            get {
                return ResourceManager.GetString("Py37ThinkingMachinesLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Last Gasp.
        /// </summary>
        internal static string Py44LastGasp {
            get {
                return ResourceManager.GetString("Py44LastGasp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://drive.google.com/file/d/1pvNzTdfV2bmMcV3i88gerQCunqOAV1GZ/view.
        /// </summary>
        internal static string Py44LastGaspLink {
            get {
                return ResourceManager.GetString("Py44LastGaspLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low-Tech Armor Design.
        /// </summary>
        internal static string Py52LTArmorDesign {
            get {
                return ResourceManager.GetString("Py52LTArmorDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://drive.google.com/file/d/0B2eXj-PYOUDMeDR3VUl4elpkc1k/view.
        /// </summary>
        internal static string Py52LTArmorDesignLink {
            get {
                return ResourceManager.GetString("Py52LTArmorDesignLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternate Guns Specialties And Techniques.
        /// </summary>
        internal static string Py65AlternateGuns {
            get {
                return ResourceManager.GetString("Py65AlternateGuns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://drive.google.com/file/d/1gW5do2k6xT0lDlTRS6CNFsBzNIcyp8m_/view.
        /// </summary>
        internal static string Py65AlternateGunsLink {
            get {
                return ResourceManager.GetString("Py65AlternateGunsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everyman Tasks.
        /// </summary>
        internal static string Py65EverymanTask {
            get {
                return ResourceManager.GetString("Py65EverymanTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://drive.google.com/file/d/1mUJLDKsSYpMdQTSN5civgHLwIXm7NWUB/view.
        /// </summary>
        internal static string Py65EverymanTaskLink {
            get {
                return ResourceManager.GetString("Py65EverymanTaskLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to А Full Complement.
        /// </summary>
        internal static string Py65FullCmplement {
            get {
                return ResourceManager.GetString("Py65FullCmplement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://drive.google.com/file/d/19HqOISDZ7Bp05hFkcyMK5SlPEcuKnph_/view.
        /// </summary>
        internal static string Py65FullCmplementLink {
            get {
                return ResourceManager.GetString("Py65FullCmplementLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cutting-Edge Armor Design.
        /// </summary>
        internal static string Py85HTArmorDesign {
            get {
                return ResourceManager.GetString("Py85HTArmorDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://drive.google.com/file/d/0B2eXj-PYOUDMWEc4UGJBdmVJS2c/view.
        /// </summary>
        internal static string Py85HTArmorDesignLink {
            get {
                return ResourceManager.GetString("Py85HTArmorDesignLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultra-Tech Armor Design.
        /// </summary>
        internal static string Py96UTArmorDesign {
            get {
                return ResourceManager.GetString("Py96UTArmorDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Cybernetics for GURPS Fourth Edition.
        /// </summary>
        internal static string PyFreeBasicCyber {
            get {
                return ResourceManager.GetString("PyFreeBasicCyber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://drive.google.com/file/d/1PrN7pYR8uKUdpI-038CuiCS-SHiYU3vY/view.
        /// </summary>
        internal static string PyFreeBasicCyberLink {
            get {
                return ResourceManager.GetString("PyFreeBasicCyberLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buzzkill.
        /// </summary>
        internal static string PyFreeBuzzkill {
            get {
                return ResourceManager.GetString("PyFreeBuzzkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://drive.google.com/file/d/1VyYTCDiS7WSBX1is_ieSbUyjo6F1MV-z/view.
        /// </summary>
        internal static string PyFreeBuzzkillLink {
            get {
                return ResourceManager.GetString("PyFreeBuzzkillLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designer&apos;s Notes GURPS Ultra-Tech.
        /// </summary>
        internal static string PyFreeDesNotesUltraTech {
            get {
                return ResourceManager.GetString("PyFreeDesNotesUltraTech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://drive.google.com/file/d/1VyYTCDiS7WSBX1is_ieSbUyjo6F1MV-z/view.
        /// </summary>
        internal static string PyFreeDesNotesUltraTechLink {
            get {
                return ResourceManager.GetString("PyFreeDesNotesUltraTechLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GURPS Accelerator Interview-Based Character Creation.
        /// </summary>
        internal static string PyFreeInterview {
            get {
                return ResourceManager.GetString("PyFreeInterview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://drive.google.com/file/d/15ihbCkPvbZMon4_rXQ9Vz440bu4lIW48/view.
        /// </summary>
        internal static string PyFreeInterviewLink {
            get {
                return ResourceManager.GetString("PyFreeInterviewLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GURPS Spaceships 1.
        /// </summary>
        internal static string Space1 {
            get {
                return ResourceManager.GetString("Space1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://drive.google.com/file/d/0B2eXj-PYOUDMYURYUnQ4SlZnOWs/view.
        /// </summary>
        internal static string Space1Link {
            get {
                return ResourceManager.GetString("Space1Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GURPS Spaceships 2.
        /// </summary>
        internal static string Space2 {
            get {
                return ResourceManager.GetString("Space2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://drive.google.com/file/d/1fHCUTDZG-5DgPuKT60Av-GowK3xoQsSV/view.
        /// </summary>
        internal static string Space2Link {
            get {
                return ResourceManager.GetString("Space2Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GURPS Spaceships 3.
        /// </summary>
        internal static string Space3 {
            get {
                return ResourceManager.GetString("Space3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://drive.google.com/file/d/1Z8aRcLnbpmp6c9Ln52I812UrH7omwFes/view.
        /// </summary>
        internal static string Space3Link {
            get {
                return ResourceManager.GetString("Space3Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GURPS Spaceships 4.
        /// </summary>
        internal static string Space4 {
            get {
                return ResourceManager.GetString("Space4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://drive.google.com/file/d/1Zu9fwgLShQfnT16-OXByQOcNmyznnw_J/view.
        /// </summary>
        internal static string Space4Link {
            get {
                return ResourceManager.GetString("Space4Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GURPS Spaceships 5.
        /// </summary>
        internal static string Space5 {
            get {
                return ResourceManager.GetString("Space5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GURPS Spaceships 6.
        /// </summary>
        internal static string Space6 {
            get {
                return ResourceManager.GetString("Space6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://drive.google.com/file/d/1UP_rMad1XPXugu06VtjSm52LjRGOEsQo/view.
        /// </summary>
        internal static string Space6Link {
            get {
                return ResourceManager.GetString("Space6Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GURPS Spaceships 7.
        /// </summary>
        internal static string Space7 {
            get {
                return ResourceManager.GetString("Space7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://drive.google.com/file/d/1UP_rMad1XPXugu06VtjSm52LjRGOEsQo/view.
        /// </summary>
        internal static string Space7Link {
            get {
                return ResourceManager.GetString("Space7Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GURPS Spaceships 8.
        /// </summary>
        internal static string Space8 {
            get {
                return ResourceManager.GetString("Space8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://drive.google.com/file/d/1Xm127ccnm83yQVgfZolN2bBB9Gh67XSM/view.
        /// </summary>
        internal static string Space8Link {
            get {
                return ResourceManager.GetString("Space8Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://drive.google.com/file/d/1sdisYrZX7tFl4mF-4lkbaPxHH4EC3-iJ/view.
        /// </summary>
        internal static string SpaceLink {
            get {
                return ResourceManager.GetString("SpaceLink", resourceCulture);
            }
        }
    }
}
